version: "3.8"

services:

  postgres: 
    image: postgres
    restart: always 
   
    environment:
    - DATABASE_HOST=127.0.0.1
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    - POSTGRES_DB=PruebaUsuario
    ports:
    - "5432:5432"
    hostname: VIP
     

    volumes: 
    - db:/var/lib/postgresql/data

  web:
    build: ./miauto.identity.api
    ports:
      - "80:80"

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on: 
      - postgres 

volumes:
  db:
    driver: local

